apiVersion: v1
kind: Secret
metadata: 
  namespace: three-tier
  name: mongo-sec
type: Opaque
data:  
  password: UHJpeWFuc2h1MTIzCg==   #Three-Tier-Project
  username: YXJ0aXNpbmdoc3RwNTMxMwo= #admin
